name: 'Objectstore Download'
description: 'Objectstore download action for DownToZero.cloud'
inputs:
  api_key:
    description: 'api key'
    required: true
  name:
    description: 'name of the artifact'
    required: true
  object_key:
    description: 'key of the objectstore, if empty name will be used'
    required: false
  continue_on_error:
    description: 'continue execution even if download fails (e.g., 404)'
    required: false
    default: 'false'
outputs:
  hit:
    description: 'true if download was successful, false otherwise'
    value: ${{ steps.download_with_key.outputs.hit || steps.download_with_name.outputs.hit }}
runs:
  using: "composite"
  steps:
    - name: downloading with object_key
      id: download_with_key
      if: ${{ inputs.object_key != '' }}
      run: |
        if [ "${{ inputs.continue_on_error }}" = "true" ]; then
          HTTP_CODE=$(curl --compressed --max-time 300 -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.object_key }}' -H 'accept: */*' -H 'X-API-KEY: ${{ inputs.api_key }}' -o ${{ inputs.name }} -w "%{http_code}" -s)
        else
          HTTP_CODE=$(curl --compressed --max-time 300 -f -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.object_key }}' -H 'accept: */*' -H 'X-API-KEY: ${{ inputs.api_key }}' -o ${{ inputs.name }} -w "%{http_code}" -s)
        fi
        if [ "$HTTP_CODE" = "200" ]; then
          echo "hit=true" >> $GITHUB_OUTPUT
        else
          echo "hit=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
    - name: downloading with artifact name
      id: download_with_name
      if: ${{ inputs.object_key == '' }}
      run: |
        if [ "${{ inputs.continue_on_error }}" = "true" ]; then
          HTTP_CODE=$(curl --compressed --max-time 300 -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.name }}' -H 'accept: */*' -H 'X-API-KEY: ${{ inputs.api_key }}' -o ${{ inputs.name }} -w "%{http_code}" -s)
        else
          HTTP_CODE=$(curl --compressed --max-time 300 -f -L 'https://objectstore.dtz.rocks/api/2022-11-28/obj/${{ inputs.name }}' -H 'accept: */*' -H 'X-API-KEY: ${{ inputs.api_key }}' -o ${{ inputs.name }} -w "%{http_code}" -s)
        fi
        if [ "$HTTP_CODE" = "200" ]; then
          echo "hit=true" >> $GITHUB_OUTPUT
        else
          echo "hit=false" >> $GITHUB_OUTPUT
        fi
      shell: bash
